# Generated by Django 5.0.3 on 2024-03-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="Forum", max_length=255),
        ),
    ]
